### ISSUE TITLE
CUDA error : no kernel image is available for execution

### ISSUE THREAD

**Issue by scarbain** [AttendAndExcite/Attend-and-Excite#7]
Hi,

Thanks for this project! Can't wait to try it out. Unfortunately, I have this error : "CUDA error : no kernel image is available for execution" on line 91 of pipeline_stable_diffusion.py.

Any idea why ? :)

**Comment by scarbain** [comment]
I reinstalled torch packages with cuda and it worked, sorry for creating an unrelated issue!

**Comment by ArielReplicate** [comment]
Hi @scarbain 
 I'm having the same problem. What torch version did you install?
 I'm installing `pip torch==1.12.0 --extra-index-url https://download.pytorch.org/whl/cu113`
 but still having this issue
